CC-6 | Import Uber konnector
cozy/cozy-konnector-uber pull request #1
Opened 2017-07-06 15:30 UTC by m4dz

2017-07-06 19:13 UTC, gregorylegarec approved these changes

2017-07-07 15:09 UTC, doubleface requested changes
Only some problems with the logging library, the rest looks good to me even if I did not test it with a valid uber account.

2017-07-07 15:09 UTC, doubleface commented on konnector.js
> +    log.info('Logging in')
Log does not come from the printit package anymore but from [this lib](https://github.com/cozy/cozy-konnector-libs/blob/master/logger.js) now. And it does not have the same interface. This line can be replaced by `log('info', 'Logging in')`

2017-07-07 15:09 UTC, doubleface commented on konnector.js
> +        log.error('Login failed')
There is now a specific error code to say that the login has failed : `LOGIN_FAILED`. You can find the long list of codes [here](https://github.com/cozy/cozy-konnector-template/blob/master/docs/ERROR_CODES.md).

This code will be interpreted by cozy-collect to display a specific error message.

2017-07-10 09:50 UTC, m4dz commented
@doubleface done, tell me if it's better now :)

2017-07-10 14:01 UTC, doubleface approved these changes
Juste le pb de log('raw') mais sinon tout m'a l'air d'être bon.

2017-07-10 14:01 UTC, doubleface commented on konnector.js
> -          log.raw(err)
Le `log('raw', ...` ne va malheureusement pas bien fonctionner puisque c'est un `JSON.stringify` qui est fait derrière. Et dans ce cas, tu vas obtenir un `{}` à la fin. Tu peux toujours faire log('info', err.message) ou faire un console.log dans cas, qui ne va pas générer de json mais ne fera pas non-plus planter la stack et affichera la stack trace en prime.

2017-07-12 09:20 UTC, m4dz commented
I've made some changes about the `log('raw', ...)`. I also updated the manifest and the Travis config to enable auto-build, let me know if it's ok (I still havent any Uber account to test the scrapping, but this part of the v2 code remains untouched)

2017-07-12 10:02 UTC, gregorylegarec commented
ping @doubleface :)

2017-07-12 10:03 UTC, merged